name: Github Actions Demo

on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - '/.github/*'
  pull_request:
    branches: main
    paths-ignore: 
      - '/.github/*'
  schedule:
    - cron: 0 6 * * 0
  workflow_dispatch:
    inputs:
      enviroments:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          ls
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing. . ."
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Testing. . ."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "Step 1 deploying. . ."
          sleep 10
      - run: |
          echo "Step 2 deploying. . ."
          sleep 10
      - run: |
          echo "Step 3 deploying. . ."
          sleep 10
      - run: |
          echo "Step 4 deploying. . ."
          sleep 10
      - run: |
          echo "Step 5 deploying. . ."
          sleep 10
      
