name: Github Actions Demo

on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - '/.github/*'
  pull_request:
    branches: main
    paths-ignore: 
      - '/.github/*'
  schedule:
    - cron: 0 6 * * 0
  workflow_dispatch:
    inputs:
      enviroments:
        description: 'Environment to deploy to'
        type: enviroment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          ls
    
