name: Reusable workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The Person to greet'
        type: string
        default: 'World'
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
